{% set name = "scico" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scico-{{ version }}.tar.gz
  sha256: a6c7ac9016a049211a5bfece91b981275abea7ee54a08733f6bb16db2f114d08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - typing_extensions
    - numpy >=1.20.0
    - scipy >=1.6.0
    - tifffile
    - imageio >=2.17
    - matplotlib-base
    - jax >=0.4.3,<=0.4.23
    - flax >=0.6.1,<=0.7.5
    - pyabel >=0.9.0
    - svmbir >=0.3.3

test:
  imports:
    - scico
    - scico.data

about:
  home: https://github.com/lanl/scico
  summary: 'Scientific Computational Imaging COde: A Python package for scientific imaging problems'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
