{% set name = "scico" %}
{% set version = "0.0.5.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scico-{{ version }}.tar.gz
  sha256: a1f808099c1aea223e3cf82a77b946a49cd27fd763dfa14c429bdf0bf0bea536

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - typing_extensions
    - numpy >=1.20.0
    - scipy >=1.6.0
    - imageio >=2.17
    - tifffile
    - matplotlib-base
    - jax >=0.4.3,<=0.4.23
    - flax >=0.6.1,<=0.7.5
    - chex >=0.1.7
    - optax >=0.1.5
    - orbax-checkpoint
    - pyabel >=0.9.0
    - xdesign >=0.5.5
    - astra-toolbox
    - svmbir >=0.3.3
    - ray-dashboard >=2.5.0
    - ray-train >=2.5.0
    - ray-tune >=2.5.0
    - hyperopt

test:
  imports:
    - scico
    - scico.data
    - scico.flax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lanl/scico
  summary: 'Scientific Computational Imaging COde: A Python package for scientific imaging problems'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
